service: echo-inventory
frameworkVersion: '4'

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs22.x
  region: us-east-1
  profile: naeem
  environment:
    TABLE_NAME: EchoInventory
    BUCKET_NAME: echo-inventory-images-local
    MODEL_ID: amazon.nova-lite-v1:0
    USER_POOL_ID: us-east-1_jh4Iug2iO
    USER_POOL_CLIENT_ID: 4n6rjfjlf2qsaj2j36r4es3l93
    IS_LOCAL: 'true'
    LOCALSTACK_ENDPOINT: http://localhost:4566

build:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    target: node22
    platform: node
    exclude: []

custom:
  serverless-offline:
    httpPort: 3001
    lambdaPort: 3002
    noPrependStageInUrl: true

functions:
  auth:
    handler: functions/auth/index.handler
    events:
      - httpApi:
          path: /auth/{proxy+}
          method: ANY

  orgs:
    handler: functions/orgs/index.handler
    events:
      - httpApi:
          path: /orgs
          method: GET
      - httpApi:
          path: /public/orgs
          method: GET
      - httpApi:
          path: /public/orgs/{proxy+}
          method: ANY

  inventory:
    handler: functions/inventory/index.handler
    events:
      - httpApi:
          path: /orgs/{orgId}/inventory
          method: ANY
      - httpApi:
          path: /orgs/{orgId}/inventory/{proxy+}
          method: ANY

  members:
    handler: functions/members/index.handler
    events:
      - httpApi:
          path: /orgs/{orgId}/members
          method: ANY
      - httpApi:
          path: /orgs/{orgId}/members/{proxy+}
          method: ANY

  image:
    handler: functions/image/index.handler
    events:
      - httpApi:
          path: /orgs/{orgId}/capture
          method: POST
      - httpApi:
          path: /public/orgs/{orgId}/capture
          method: POST
